all: p1-fork p2-wait p3-exec p4-redirect piping shellLab

p1-fork: p1-fork.o
p2-wait: p2-wait.o
p3-exec: p3-exec.o
p4-redirect: p4-redirect.o
piping: piping.o
shellLab: shellLab

clean:
	rm -f *.o p1-fork p2-wait p3-exec p4-redirect p4-output.txt piping shellLab
